config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users 

  get 'users/sign_up'

  resources :categories do
    resources :tasks
  end
  
  root 'categories#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :tasks
    
    validates :title, presence: true, uniqueness: true
    validates :description, presence: true

end

app/models/task.rb
class Task < ApplicationRecord
    # belongs_to :user
    belongs_to :category
    
    
    validates :category_id, presence: true
    validates :name, presence: true, uniqueness: true
    validates :description, presence: true
    validates :date, presence: true
    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # has_many :task
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
 

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end

  def new
    @category = Category.new
  end

  def edit
    @category = Category.find(params[:id])
  end

  def create
    @category = Category.new(category_params)

    if @category.save
        redirect_to @category, notice: 'Category was successfully created!' 
    else
        render :new
    end
  end

  def update
    @category = Category.find(params[:id])

    if @category.update(category_params)
        redirect_to @category, notice: 'Category was successfully updated!' 
    else
        render :edit
    end
  end

  def destroy
    @category.destroy
    redirect_to categories_url, notice: 'category was successfully destroyed.'
  end

  private 
  
  def category_params
      params.require(:category).permit(:title, :description)
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    def create
        @category = Category.find(params[:category_id])
        @task = @category.tasks.create(task_params)
        redirect_to category_path(@category)
    end

    def delete
        @category = Category.find(params[:category_id])
        @task = @category.tasks.create(task_params)
        @task.delete
        redirect_to category_path(@category)
    end
    

    private

    def task_params
        params.require(:task).permit(:category_id, :name, :description, :date)
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, :class => 'form-control-sm' %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_field :description, :class => 'form-control-sm' %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Edit Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<table class="table table-striped">
  <thead class="thead-dark">
    <tr>
      <th scope="col" >Title</th>
      <th scope="col">Description</th>
      <% if current_user %>
      <th colspan="3" scope="col">Actions</th>
      <%end%>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.title %></td>
        <td><%= category.description %></td>
        <% if current_user %>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Delete', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<button class="btn btn primary"><%= link_to 'New category', new_category_path %></button> 
<hr>

<% if current_user %>
  <button class="btn btn primary"><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></button>
<% else %>
  <button class="btn btn primary"><%= link_to 'Sign up', new_user_registration_path %></button> |
  <button class="btn btn primary"><%= link_to 'Sign in', new_user_session_path %></button>
<% end %>
<hr>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<h4>Category</h4><br>
<p>
  <strong>Title:</strong>
  <%= @category.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @category.description %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

<hr>
<hr>
<h4>Tasks</h4><br>

<div class="well">
    <table class="table table-striped">
      <thead class="thead-dark">
        <tr>
          <th scope="col" >ID</th>
          <th scope="col" >Name</th>
          <th scope="col">Description</th>
          <th scope="col">Date</th>
          <th colspan="2" scope="col">Actions</th>
        </tr>
      </thead>

      <tbody>
        <% @category.tasks.each do |task| %>
          <tr>
            <td><%= task.category_id %></td>
            <td><%= task.name %></td>
            <td><%= task.description %></td>
            <td><%= task.date.strftime('%b %d %Y') %></td>
            <td><%= link_to 'Delete', [task.category, task], method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
</div>  

<hr>
<hr>

<h4>Add Task</h4><br>

<%= form_for([@category, @category.tasks.build]) do |form| %>

 <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, :class => 'form-control-sm' %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_field :description, :class => 'form-control-sm' %>
  </div>

 <div class="form-group">
    <%= form.label :date %>
    <%= form.date_field :date, :class => 'form-control-sm' %>
  </div>

  <div class="actions">
    <%= form.submit({:class => 'btn btn-default'}) %>
  </div>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JournalApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  
  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%# <%= form_with model: [@category, @task ], local: true do |form| %>
<%= form_for([@category, @category.tasks.create]) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>
      <ul>
        <% task.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :category_id %>
    <%= form.select :category_id, options_from_collection_for_select(Category.all, :id, :title), :class => 'form-control-sm' %>
  </div>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, :class => 'form-control-sm' %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_field :description, :class => 'form-control-sm' %>
  </div>

 <div class="form-group">
    <%= form.label :date %>
    <%= form.date_field :date, :class => 'form-control-sm' %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Edit Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Show', category_task_path %> |
<%= link_to 'Back', category_tasks_path %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tasks</h1>

<table class="table table-striped">
  <thead class="thead-dark">
    <tr>
      <th scope="col" >ID</th>
      <th scope="col" >Name</th>
      <th scope="col">Description</th>
      <th scope="col">Date</th>
      <th colspan="2" scope="col">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @category.tasks.each do |task| %>
      <tr>
        <td><%= task.category_id %></td>
        <td><%= task.name %></td>
        <td><%= task.description %></td>
        <td><%= task.date.strftime('%B %d %Y') %></td>
        <% if current_user && current_user.admin %>
          <td><%= link_to 'Edit',  url_for([task.category, task]) %></td>
          <td><%= link_to 'Delete', [task.category, task], method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<button class="btn btn primary"><%= link_to 'New task', new_category_task_path %></button> |
<button class="btn btn primary"><%= link_to 'Back to Categories', categories_path %></button>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>ID:</strong>
  <%= @task.category_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @task.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @task.description %>
</p>

<p>
  <strong>Date:</strong>
  <%= @task.date %>
</p>

<%= link_to 'Edit', edit_category_task_path(@task) %> |
<%= link_to 'Back', category_tasks_path %>